server:
  http_listen_port: 8000

search_enabled: true

distributor:
  log_received_traces: true
  receivers:
    otlp:
      protocols:
        http:
        grpc:

storage:
  trace:
    backend: local
    block:
      encoding: zstd
    wal:
      path: /tmp/tempo/wal
      encoding: none
    local:
      path: /tmp/tempo/blocks
